version: "3"

services:
  postgres:
    image: 'postgres:14-alpine'
    hostname: postgres
    container_name: starter-postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=starter
    restart: always
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data

  api:
    image: node:16-alpine
    container_name: starter-api
    restart: always
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - 3333:3333
    command: npm -w api run dev
    depends_on:
      - mongo

volumes: 
  db:
